### ISSUE TITLE
out of memory when running on jetson nano

### ISSUE THREAD

**Issue by vtn98** [phamvanhanh6720/Face-Recognition#3]
hi @phamvanhanh6720,
I tried your project on jetson nano, but I cannot load embbedding model because raise out of memory.
How can you run your project on jetson nano?
please, help me!

**Comment by phamvanhanh6720** [comment]
You can extend swap partition and use [tip](https://www.youtube.com/watch?v=9bACmWg0bvs&ab_channel=JetsonHacks)
